### ISSUE TITLE
/metrics end point not returning data

### ISSUE THREAD

**Issue by aww-yiss** [EinsamHauer/disthene-reader#7]
updated from 0.2.28 to 0.2.30 which incorporates the latest changes for relative time parsing, and seeing that when issuing a request for /metrics  this is only returning an empty series list

```
{"from":1459515060,"to":1459515300,"step":60,"series":{}}
```

However issuing the same series query to /render returns all the data as expected, also confirmed that by reverting to 0.2.28 tag'd build works as expected for both. 

Not seeing anything in the diffs that would have affected the /metrics endpoint between these two, so this is rather puzzling.

For reference this is being queried using the graphite-api and graphite-cyanite custom finder.

**Comment by EinsamHauer** [comment]
@aww-yiss Hmm. Are you sure it works with 0.2.28? To me at looks like it's broken since ages...

**Comment by EinsamHauer** [comment]
The last commit should fix it I hope. Please check

**Comment by aww-yiss** [comment]
@EinsamHauer yes I can confirm this has fixed it. :+1: 

I _may_ have been mistaken about testing OK on the prior release version being 0.2.28 but the jar was label as such when it was built from maven.
